#!/usr/bin/env bash
# SPDX-License-Identifier: Apache-2.0
#
# scripts/lib/emit_ledger.sh — produce results/LEDGER.md, the single
# human-readable summary a judge (or $GITHUB_STEP_SUMMARY) can read without
# opening every log file.
#
# If tools/emit_ledger.py or tools/emit_ledger.sh exists, it is preferred
# (it can parse the actual dispatch-sweep / bench JSON into a rich table).
# Otherwise this falls back to a minimal ledger built purely from
# results/stage-status.tsv (written by every stage via
# scripts/common.sh:record_stage) plus a directory listing of whatever
# landed under results/ — so the artifact is never empty, even before
# tools/ has an emit_ledger implementation.
set -euo pipefail
LIB_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=scripts/common.sh
source "$LIB_DIR/../common.sh"

STAGE="emit_ledger"
LEDGER_PATH="$RESULTS_DIR/LEDGER.md"

entrypoint="$(find_entrypoint tools emit_ledger || true)"
if [[ -n "$entrypoint" ]]; then
    log_info "found ledger tool: $entrypoint"
    if RESULTS_DIR="$RESULTS_DIR" OUTPUT_PATH="$LEDGER_PATH" run_entrypoint "$entrypoint" \
        >"$LOG_DIR/emit_ledger.log" 2>&1; then
        record_stage "$STAGE" OK "wrote $LEDGER_PATH via $entrypoint"
        exit 0
    else
        log_warn "tools/emit_ledger failed (see $LOG_DIR/emit_ledger.log); falling back to the built-in minimal ledger"
    fi
fi

# --- fallback: minimal ledger from stage-status.tsv + a results/ listing ---
{
    echo "# Polygraph — run summary"
    echo
    echo "_Generated by scripts/lib/emit_ledger.sh's built-in fallback"
    echo "(no tools/emit_ledger found or it failed — see"
    echo "scripts/common.sh CROSS-PACKAGE CONTRACT). Generated:"
    echo "$(date -u +'%Y-%m-%dT%H:%M:%SZ')_"
    echo
    echo "## Stage results"
    echo
    echo "| stage | status | message |"
    echo "|---|---|---|"
    if [[ -f "$STAGE_STATUS_FILE" ]]; then
        while IFS=$'\t' read -r _ts name status message; do
            echo "| $name | $status | $message |"
        done <"$STAGE_STATUS_FILE"
    else
        echo "| (none) | - | no stages recorded yet |"
    fi
    echo
    echo "## Files under results/"
    echo
    find "$RESULTS_DIR" -type f ! -name 'LEDGER.md' | sed "s|^$RESULTS_DIR/|- |" | sort
} >"$LEDGER_PATH"

record_stage "$STAGE" OK "wrote fallback ledger to $LEDGER_PATH"
